#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_hwicap_v2_02_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_hwicap_v2_02_a/virtex6/axi_hwicap_lite_mode_68097_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_hwicap_v2_02_a/virtex6/axi_hwicap_read_intr_80921_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_hwicap_v2_02_a/virtex6/axi_hwicap_wr_intr_99630_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_hwicap_v2_02_a/virtex6/axi_hwicap_def_18499_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]