#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_timebase_wdt_v1_01_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_v7_92888_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_interrupt_fcs4_51748_9/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex7/wdt_fcs5_35974_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qspartan6/wdt_fcs5_35974_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qspartan6/wdt_fcs5_35974_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qspartan6/wdt_fcs2_52660_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_interrupt_fcs4_51748_7/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_interrupt_fcs4_51748_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_zynq_11779_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/zynq/wdt_fcs3_82728_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qvirtex6/wdt_fcs3_82728_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qvirtex6/wdt_fcs2_52660_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qvirtex6/wdt_fcs3_82728_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qvirtex6/wdt_fcs2_52660_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_fcs5_35974_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_interrupt_fcs4_51748_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_a7_13942_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/artix7/wdt_fcs2_52660_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/qspartan6l/wdt_fcs3_82728_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_interrupt_fcs4_51748_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_fcs5_35974_7/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_k7_35176_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/kintex7/wdt_interrupt_fcs4_51748_8/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/aspartan6/wdt_interrupt_fcs4_51748_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/aspartan6/wdt_fcs5_35974_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex6/wdt_interrupt_fcs4_51748_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/virtex6/wdt_interrupt_fcs4_51748_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/spartan6/wdt_fcs5_35974_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/spartan6/wdt_fcs1_16901_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/spartan6/wdt_fcs5_35974_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_timebase_wdt_v1_01_a/spartan6l/wdt_interrupt_fcs4_51748_5/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]