#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_dma_v6_00_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_1_20479_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_1_20479_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_mch_26993_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_2_59822_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_2_59822_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_1_20479_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_2_59822_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_mch_26993_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_1_20479_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_mch_26993_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_2_59822_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_2_59822_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_1_20479_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_mch_26993_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/virtex7/axi_dma_mm2s_mch_26993_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_2_46443_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_2_46443_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_2_46443_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_1_56839_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_1_56839_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_2_46443_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_1_56839_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_2_46443_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_1_56839_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_dma_v6_00_a/kintex7/axi_dma_s2mm_1_56839_1/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]