#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_cdma_v3_02_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/virtex6l/axi_cdma_simple_large_pkt_73491_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/virtex6l/axi_cdma_simple_all_56078_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/virtex6cx/axi_cdma_dlycntr_88289_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/qvirtex6/axi_cdma_sg_large_pkt_98694_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/qvirtex6/axi_cdma_simple_sg_95117_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/qspartan6l/axi_cdma_simple_async_84386_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/aspartan6/axi_cdma_sg_all_10152_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/aspartan6/axi_cdma_sg_95083_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/aspartan6/axi_cdma_sg_async_57535_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/aspartan6/axi_cdma_sg_sf_83927_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/spartan6l/axi_cdma_simple_47801_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_cdma_v3_02_a/spartan6l/axi_cdma_simple_sf_39354_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]