#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_emc_v1_02_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex7/aemc_sram_129_256len_17135_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex7/aemc_sram_129_256len_17135_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex7/aemc_sram_129_256len_17135_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex7/aemc_sram_129_256len_17135_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6/aemc_byteparity_58818_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6/aemc_pgflash_92234_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6/aemc_byteparity_58818_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex6l/aemc_reset_psram_14998_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/zynq/aemc_lflash_17423_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qvirtex6/aemc_pgflash_92234_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/artix7/aemc_sram_fixed_len_37188_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/artix7/aemc_lflash_17423_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6l/aemc_reset_psram_14998_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6l/aemc_pgflash_92234_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/qspartan6l/aemc_reset_sram_97894_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/kintex7/aemc_sram_1_128len_50463_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/kintex7/aemc_sram_1_128len_50463_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/kintex7/aemc_sram_1_128len_50463_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/kintex7/aemc_sram_1_128len_50463_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/kintex7/aemc_sram_1_128len_50463_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/aspartan6/aemc_psram_25196_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/aspartan6/aemc_psram_25196_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex6/aemc_sram_fixed_len_37188_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex6/aemc_reset_sram_97894_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/virtex6/aemc_byteparity_58818_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_emc_v1_02_a/spartan6/aemc_byteparity_58818_3/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]