#!/tools/xgs/perl/5.8.5/bin/perl
use warnings;
use strict; 

my $dir_date = localtime(); 
my @dte_splt = split /\s+/, $dir_date; 		# 0->day, 1->Month, 2->date, 3->time, 4->year
if ($dte_splt[2] < 10) {$dte_splt[2] = "0$dte_splt[2]";}
my %mnth     =  (Jan =>"01", Feb =>"02", Mar =>"03", May =>"05", Apr =>"04", Jun=>"06", 
	         Jul=>"07", Aug=>"08", Sep=>"09", Oct=>"10", Nov=>"11", Dec=>"12");
my $mth_no   = $mnth{$dte_splt[1]}; # map the corresponding # accroding to month
my $cntd     = 0; my $cntf =0; my @mjr_rng = (14 .. 24); my @min_rng = (1..5);
my $dir_name = "$mjr\.$min_".$mth_no.$dte_splt[2]; 
my $file = "tda-info.txt";
my $msgdf    = "Directory ".$dir_name." not found.\n";
my $msgf     = "Directory ".$dir_name. " are there but File ".$file." do not found.\n";
my $msgs     = "Directory: ".$dir_name." and\nFile: ".$file."\nare ready to use. \n";
my $sign     = "\n\nThanks & Regards\nAnkit Kotak\nIP Verification Engineer \nXilinx Inc, San Jose\nDesk: +1 408 879 7704\nCell: +1 201 668 1920";
my $fd_chk = "/home/ankitko/scripts/df_exist"; 
#------------------------------------------------------------------------------------------------
					
	sub suc_mail{
	    my $msg = shift;
	    open (SENDMAIL,"|/usr/lib/sendmail -oi -t -odq")or die"Can't fork for sendmail: $!\n";
    	    print SENDMAIL "From:Ankit Kotak<ankitko\@xilinx.com> \n";
    	    print SENDMAIL "To:<ankit.kotak\@xilinx.com>\n";
    	    print SENDMAIL "Subject:Update for directory ".$dir_name ."and file ".$file."\n";
   	    print SENDMAIL "Hello Admin,\n\n";
    	    print SENDMAIL $msg;
	    print SENDMAIL $sign;
    	    close(SENDMAIL) or warn "sendmail didn't close nicely";
	    0; }
#----------------------------------------------------------------------------------------------

foreach $maj (@mjr_rng){

	foreach $min (@min_rng){
	
	print $dir_name; 
	
	
	
	}




}    
if(-e $fd_chk_$dir_name) {

print "Do nothing\n	";	
}

else{
opendir (DCHECK, "/proj/xbuilds/") or die $!;
	while($_ = readdir(DCHECK)){
		if($_ eq $dir_name){
			$cntd = $cntd+1; 
		}
		
	}

	if($cntd==0)
	{
	  #&suc_mail($msgdf);
	}
	else {
	  opendir (FCHECK,"/proj/xbuilds/$dir_name") or die $!;
		while($_=readdir(FCHECK)){
			if($_ eq $file){
				$cntf= $cntf+1;
				&suc_mail($msgs); 			
				open DFE, ">$fd_chk_$dir_name" or die $!;
				print DFE "Directory & files are ready to use";
			}
		 
		
		}
		if($cntf==0){
				#&suc_mail($msgf);
		}
	}
}
