#!/bin/csh 
#BSUB -J ahblite_axi_bridge_v1_00_a_random[1-20]
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]"
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/virtex6l/ahb2axi_err_23341_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/virtex6l/ahb2axi_narrow_burst_34140_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/artix7/ahb2axi_default_28840_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/kintex7/ahb2axi_k7_90994_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/virtex6/ahb2axi_narrow_burst_34140_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/spartan6/ahb2axi_timeout_42731_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/spartan6l/ahb2axi_burst_71037_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/ahblite_axi_bridge_v1_00_a/spartan6l/ahb2axi_burst_71037_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]
