#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_uart16550_v1_01_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/virtex7/uart550_v7_22523_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/virtex7/uart550_v7_1_84155_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/qspartan6/uart_fcs1_21493_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/zynq/uart550_zynq_39340_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/zynq/uart550_zynq_1_30188_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/kintex7/uart550_k7_1_26323_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/kintex7/uart550_k7_36982_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/virtex6/uart_fcs1_1_69745_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_uart16550_v1_01_a/virtex6/uart_fcs2_52983_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]