#!/bin/csh 
#BSUB -J axi_apb_bridge_v1_00_a_random[1-20]
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" 
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_97486_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex7/apb_bridge_random_v7_43572_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/qspartan6/apb_bridge_basic_13693_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/qspartan6/apb_bridge_random_97486_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/virtex6l/apb_bridge_random_97486_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/zynq/apb_bridge_random_z_29343_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/qvirtex6/apb_bridge_random_97486_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/artix7/apb_bridge_random_a7_23150_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/kintex7/apb_bridge_random_k775399_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/aspartan6/apb_bridge_random_97486_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_apb_bridge_v1_00_a/aspartan6/apb_bridge_random_97486_0/input \
);
/home/ankitko/scripts/EDK_Rohit/lsf_wrapper_lin.csh $a[$LSB_JOBINDEX];
