#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_iic_v1_02_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/qspartan6/iic_random1_71385_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/qspartan6/iic_random1_71385_9/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/qspartan6/iic_random1_71385_7/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/virtex6l/iic_random1_71385_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/virtex6l/iic_random1_71385_18/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/zynq/iic_random1_71385_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/zynq/iic_random1_71385_6/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/zynq/iic_random1_71385_16/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/artix7/iic_random1_71385_10/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/artix7/iic_random1_71385_8/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/qspartan6l/iic_random1_71385_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/kintex7/iic_random1_71385_14/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/kintex7/iic_random1_71385_12/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/aspartan6/iic_random1_71385_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/virtex6/iic_default_99115_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/virtex6/iic_random1_71385_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/virtex6/iic_default_99115_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/spartan6/iic_random1_71385_19/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/spartan6l/iic_random1_71385_17/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/spartan6l/iic_random1_71385_13/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/spartan6l/iic_random1_71385_15/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_iic_v1_02_a/spartan6l/iic_random1_71385_11/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]