#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_ahblite_bridge_v1_00_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/virtex7/ahb_bridge_basic_44905_3/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/virtex6l/ahb_bridge_basic_44905_2/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/zynq/ahb_bridge_basic_44905_4/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/qvirtex6/ahb_bridge_basic_44905_1/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/artix7/ahb_bridge_basic_44905_5/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/virtex6/ahb_bridge_basic_44905_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ahblite_bridge_v1_00_a/spartan6l/ahb_bridge_random_22552_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]