#!/bin/csh 
#BSUB -P ip_ipv_regressions -Lp ips_ipv_grp -R "select[type==X86_64 && os==lin]" -R "rusage[mem=3000]" -J axi_ethernet_v3_01_a_random[1-20]%100
#BSUB -eo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.err
#BSUB -oo /proj/xtools/testRunner/logs/ankitko/%J_%I_xlnxIP.txt
set a = (\
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/BASEX1000_1G_3_10845_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/RGMII_2_0_100_265418_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/RGMII_2_0_1G_2_20564_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/MII_100_CSUM_AVB_STATS_98871_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/SGMII_100_CSUM_AVB_STATS_29392_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/MII_100_1_75066_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex7/RGMII_2_0_1G_1_44149_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/kintex7/BASEX1000_1G_2_68273_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/kintex7/RGMII_2_0_100_1_58441_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/kintex7/BASEX1000_1G_1_77717_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/kintex7/SGMII_1G_2_41230_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/GMII_1G_CSUM_AVB_STATS_18856_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/SGMII_1G_361986_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/SGMII_1G_1_45454_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/BASEX1000_1G_CSUM_AVB_STATS_20403_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/GMII_100_2_11429_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/GMII_100_1_31836_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/RGMII_2_0_1G_CSUM_AVB_STATS_89905_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/virtex6/RGMII_2_0_1G_3_27937_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/spartan6/GMII_10_13142_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/spartan6/GMII_100_CSUM_AVB_STATS_98374_0/input \
/proj/xtcRepo/ipv/epdIP/14.2_0516/FOCUS/_TCASE/edkIP/axi_ethernet_v3_01_a/spartan6/MII_100_2_39286_0/input \
);
./lsf_wrapper_lin.csh $a[$LSB_JOBINDEX]